#!/usr/bin/env bash
# Configuring Nginx server to have a custom 404 page and 301 redirect

apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html

# Configure 301 redirection
sed -i '/^\tserver_name.*/a \\tlocation /redirect_me {\n\treturn 301 https://www.google.com;\n\t}' /etc/nginx/sites-available/default

# Configure custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i '/^\tserver_name.*/a \\terror_page 404 /404.html;\n\tlocation = /404.html {\n\troot /var/www/html;\n\tinternal;\n\t}' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx restart

